django_api/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('keras_model.urls')),
]

keras_model/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings



app_name = 'keras_model'
urlpatterns = [
    path('', views.index, name='index'),
    path('image/', views.predict_Image, name='image'),
]

keras_model/forms.py
from django import forms

class UploadFileForm(forms.Form):
    image = forms.ImageField()

keras_model/views.py
from django.shortcuts import render
from .forms import UploadFileForm
from .predict import predict


def index(request):
    return render(request, "keras_model/index.html")

def save_uploaded_image(f,name):
    with open("keras_model/static/media/"+ "temp.png", "wb+") as destination:
        for chunk in f.chunks():
            destination.write(chunk)

# Create your views here.
def predict_Image(request):
    if request.method == "POST":
        form = UploadFileForm(request.POST, request.FILES)
        if form.is_valid():
            image=request.FILES['image']
            save_uploaded_image(image, image._name)

            result = predict("keras_model/static/media/"+ "temp.png")[0][1]


            resp = {'data':"http://127.0.0.1:8000/static/media/"+ image._name , 'result': result}
            return render(request, "keras_model/result.html", resp)

    else:
        return render(request, "keras_model/index.html")

keras_model/templates/keras_model/index.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Угадайка</title>
  <link rel="stylesheet" href="{% static 'css/form.css' %}">
  <link rel="stylesheet" href="{% static 'css/upload.css' %}">
</head>

<body>


        <form action= "{% url 'keras_model:image' %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form">
                    <div class="form__title">Угадайка (Hushchyn Danil creator)</div>
                   <div class="form__row">
                       <input class=" form__horizontal-img" name="image" type="file">
                  </div>

            </div>

        </form>


</div>
     <script>
         let urlImgRemove = "{% static 'imgs/remove.png' %}";
      </script>
   <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
   <script type="module" src="{% static 'js/index.js' %}"></script>
</body>
</html>

keras_model/templates/keras_model/result.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>

    <meta charset="UTF-8">
    <title>Keras Model Prediction results</title>

</head>
<body style="background: #FAE596">
<h1>Keras Model Prediction results</h1>
<h2>The prediction results is: {{ result }}</h2>
<img src =" {% static "media/temp.png" %}" style="width: 300px;height: 250px">
</body>
</html>